using System;

namespace Fulcrum.Core.Relative
{
    /// <summary>
    /// Reusable output generated by the RelativeCalculator.
    ///
    /// Contains ordered cars ahead and behind the player.
    /// </summary>
    public sealed class RelativeSnapshot
    {
        public const int DefaultEntryCapacity = 8;

        private readonly RelativeEntry[] aheadEntries;
        private readonly RelativeEntry[] behindEntries;

        public RelativeSnapshot()
            : this(DefaultEntryCapacity)
        {
        }

        public RelativeSnapshot(
            int entryCapacity)
        {
            if (entryCapacity <= 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(entryCapacity),
                    "Relative entry capacity must be greater than zero.");
            }

            aheadEntries =
                new RelativeEntry[entryCapacity];

            behindEntries =
                new RelativeEntry[entryCapacity];

            for (int index = 0;
                 index < entryCapacity;
                 index++)
            {
                aheadEntries[index] =
                    new RelativeEntry();

                behindEntries[index] =
                    new RelativeEntry();
            }

            Reset();
        }

        public bool HasValidPlayer
        {
            get;
            private set;
        }

        public int PlayerCarIndex
        {
            get;
            private set;
        }

        public double PlayerContinuousTrackPosition
        {
            get;
            private set;
        }

        public int AheadCount
        {
            get;
            internal set;
        }

        public int BehindCount
        {
            get;
            internal set;
        }

        public int Capacity
        {
            get
            {
                return aheadEntries.Length;
            }
        }

        public RelativeEntry GetAhead(
            int index)
        {
            if (index < 0 ||
                index >= aheadEntries.Length)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(index));
            }

            return aheadEntries[index];
        }

        public RelativeEntry GetBehind(
            int index)
        {
            if (index < 0 ||
                index >= behindEntries.Length)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(index));
            }

            return behindEntries[index];
        }

        internal void SetPlayer(
            int playerCarIndex,
            double continuousTrackPosition)
        {
            HasValidPlayer = true;

            PlayerCarIndex =
                playerCarIndex;

            PlayerContinuousTrackPosition =
                continuousTrackPosition;
        }

        public void Reset()
        {
            HasValidPlayer = false;

            PlayerCarIndex = -1;
            PlayerContinuousTrackPosition = 0.0;

            AheadCount = 0;
            BehindCount = 0;

            for (int index = 0;
                 index < aheadEntries.Length;
                 index++)
            {
                aheadEntries[index].Reset();
                behindEntries[index].Reset();
            }
        }
    }
}